name:                fourier
version:             0.1.0.0
github:              "juliagracedefoor/fourier"
license:             BSD3
author:              "Julia DeFoor"
maintainer:          "juliagracedefoor@gmail.com"
copyright:           "Julia DeFoor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juliagracedefoor/fourier#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  fourier-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fourier

tests:
  fourier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fourier
